const groups = {
  normal: ['あ','い','う','え','お','か','き','く','け','こ','さ','し','す','せ','そ','た','ち','つ','て','と','な','に','ぬ','ね','の','は','ひ','ふ','へ','ほ','ま','み','む','め','も','ら','り','る','れ','ろ','わ','を','ん'],
  voiced: ['が','ぎ','ぐ','げ','ご','ざ','じ','ず','ぜ','ぞ','だ','ぢ','づ','で','ど','ば','び','ぶ','べ','ぼ','ぱ','ぴ','ぷ','ぺ','ぽ'],
  contracted: ['きゃ','きゅ','きょ','しゃ','しゅ','しょ','ちゃ','ちゅ','ちょ','にゃ','にゅ','にょ','ひゃ','ひゅ','ひょ','みゃ','みゅ','みょ','りゃ','りゅ','りょ']
};
const labels = {
 zh:{ practiceSet:'练习词库',chooseSet:'选择你的练习',setHint:'按需组合假名，开始一组轻松的书写练习。',vocabulary:'词库',customSelection:'手动选择',selectAll:'全选',startPractice:'开始练习',writeThis:'照着写',skip:'换一个',writingArea:'书写区',shortcut:'按住鼠标或手指书写',pencil:'铅笔',eraser:'橡皮',clear:'清除笔迹',next:'下一题 →',normal:'普通',voiced:'第一等级变形',contracted:'加上 ya / yu / yo 的格式',question:'第 {n} / {total} 题',meaning:'读音：{roman}' },
 ja:{ practiceSet:'練習セット',chooseSet:'練習をえらぶ',setHint:'ひらがなを組み合わせて、書く練習を始めましょう。',vocabulary:'単語帳',customSelection:'手動で選ぶ',selectAll:'すべて選択',startPractice:'練習をはじめる',writeThis:'お手本どおりに書く',skip:'スキップ',writingArea:'書くところ',shortcut:'マウスか指で書けます',pencil:'えんぴつ',eraser:'けしごむ',clear:'消去',next:'つぎへ →',normal:'基本',voiced:'濁音・半濁音',contracted:'拗音（ゃ / ゅ / ょ）',question:'{n} / {total} 問',meaning:'読み：{roman}' },
 ko:{ practiceSet:'연습 세트',chooseSet:'연습을 선택하세요',setHint:'히라가나를 골라 즐겁게 쓰기 연습을 시작하세요.',vocabulary:'단어장',customSelection:'직접 선택',selectAll:'전체 선택',startPractice:'연습 시작',writeThis:'따라 써 보세요',skip:'바꾸기',writingArea:'쓰기 영역',shortcut:'마우스나 손가락으로 쓰세요',pencil:'연필',eraser:'지우개',clear:'지우기',next:'다음 →',normal:'기본',voiced:'1단 변형',contracted:'ya / yu / yo 조합',question:'{n} / {total} 번',meaning:'발음: {roman}' },
 en:{ practiceSet:'Practice set',chooseSet:'Choose your practice',setHint:'Mix and match kana for a calm writing session.',vocabulary:'Vocabulary set',customSelection:'Choose manually',selectAll:'Select all',startPractice:'Start practice',writeThis:'Copy this',skip:'Skip',writingArea:'Writing area',shortcut:'Write with mouse or finger',pencil:'Pencil',eraser:'Eraser',clear:'Clear strokes',next:'Next →',normal:'Basic',voiced:'Level 1 variations',contracted:'ya / yu / yo forms',question:'Question {n} / {total}',meaning:'Sound: {roman}' }
};
const vocabulary = {
 zh:{all:'全部假名',basic:'基础五十音',voiced:'变形假名',contracted:'拗音练习'},
 ja:{all:'すべてのひらがな',basic:'基本の五十音',voiced:'濁音・半濁音',contracted:'拗音'},
 ko:{all:'모든 히라가나',basic:'기본 오십음',voiced:'변형 히라가나',contracted:'요음 연습'},
 en:{all:'All hiragana',basic:'Basic gojūon',voiced:'Voiced variations',contracted:'Contracted sounds'}
};
const roman = {あ:'a',い:'i',う:'u',え:'e',お:'o',か:'ka',き:'ki',く:'ku',け:'ke',こ:'ko',さ:'sa',し:'shi',す:'su',せ:'se',そ:'so',た:'ta',ち:'chi',つ:'tsu',て:'te',と:'to',な:'na',に:'ni',ぬ:'nu',ね:'ne',の:'no',は:'ha',ひ:'hi',ふ:'fu',へ:'he',ほ:'ho',ま:'ma',み:'mi',む:'mu',め:'me',も:'mo',ら:'ra',り:'ri',る:'ru',れ:'re',ろ:'ro',わ:'wa',を:'wo',ん:'n'};
const $ = s => document.querySelector(s); let language = 'zh', currentSet = [...groups.normal], queue = [], index = 0, tool = 'pencil';
function t(key){ return labels[language][key] || key; }
function applyLanguage(){ document.documentElement.lang=language; document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n)); renderGroups(); renderVocab(); updateQuestion(); }
function renderVocab(){ const select=$('#vocabSelect'), previous=select.value; select.innerHTML=''; Object.entries(vocabulary[language]).forEach(([value,text])=>{const o=new Option(text,value);select.add(o)}); select.value=previous || 'all'; }
function renderGroups(){ const root=$('#kanaGroups'); root.innerHTML=''; Object.entries(groups).forEach(([key,kana])=>{ const section=document.createElement('section');section.className='kana-group';section.innerHTML=`<div class="group-title">${t(key)}</div><div class="kana-options">${kana.map(k=>`<label title="${k}"><input type="checkbox" value="${k}" checked><span>${k}</span></label>`).join('')}</div>`;root.append(section); }); }
function selectedKana(){ return [...document.querySelectorAll('.kana-options input:checked')].map(x=>x.value); }
function makeQueue(){ const chosen=selectedKana(); currentSet=chosen.length?chosen:[...groups.normal]; queue=[...currentSet].sort(()=>Math.random()-.5); index=0; updateQuestion(); clearCanvas(); }
function updateQuestion(){ const kana=queue[index] || currentSet[0] || 'あ'; $('#currentKana').textContent=kana; $('#canvasGuide').textContent=kana; $('#questionMeaning').textContent=t('meaning').replace('{roman}',roman[kana] || kana); $('#progressText').textContent=t('question').replace('{n}',index+1).replace('{total}',queue.length || 1); $('#progressBar').style.width=`${((index+1)/(queue.length||1))*100}%`; }
function next(){ if(!queue.length)makeQueue(); else { index=(index+1)%queue.length; updateQuestion(); clearCanvas(); } }
$('#languageSelect').addEventListener('change',e=>{language=e.target.value;applyLanguage()}); $('#startPractice').addEventListener('click',makeQueue); $('#selectAll').addEventListener('click',()=>document.querySelectorAll('.kana-options input').forEach(i=>i.checked=true)); $('#vocabSelect').addEventListener('change',e=>{ const sets={all:[...groups.normal,...groups.voiced,...groups.contracted],basic:groups.normal,voiced:groups.voiced,contracted:groups.contracted}; const wanted=new Set(sets[e.target.value]);document.querySelectorAll('.kana-options input').forEach(i=>i.checked=wanted.has(i.value)); }); $('#nextButton').addEventListener('click',next); $('#skipButton').addEventListener('click',next); $('#clearButton').addEventListener('click',clearCanvas);
function selectTool(name){ tool=name; $('#pencilButton').classList.toggle('active',name==='pencil');$('#eraserButton').classList.toggle('active',name==='eraser');$('#pencilButton').setAttribute('aria-pressed',name==='pencil');$('#eraserButton').setAttribute('aria-pressed',name==='eraser');canvas.style.cursor=name==='eraser'?'cell':'crosshair'; } $('#pencilButton').onclick=()=>selectTool('pencil');$('#eraserButton').onclick=()=>selectTool('eraser');
const canvas=$('#writingCanvas'), ctx=canvas.getContext('2d'); let drawing=false,last=null; function sizeCanvas(){ const box=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1; const data=canvas.width?canvas.toDataURL():null;canvas.width=box.width*ratio;canvas.height=box.height*ratio;ctx.scale(ratio,ratio); if(data){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,box.width,box.height);img.src=data;} } function clearCanvas(){ctx.clearRect(0,0,canvas.width,canvas.height)} function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}} function draw(e){if(!drawing)return;const p=point(e);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=tool==='eraser'?28:5;ctx.strokeStyle=tool==='eraser'?'#fffefa':'#263046';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;} canvas.addEventListener('pointerdown',e=>{drawing=true;last=point(e);canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',draw);['pointerup','pointercancel','pointerleave'].forEach(event=>canvas.addEventListener(event,()=>drawing=false)); window.addEventListener('resize',sizeCanvas); $('#soundButton').addEventListener('click',()=>{const kana=$('#currentKana').textContent; speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(kana));});
applyLanguage(); sizeCanvas(); makeQueue();
