const groups = {
  normal: ['あ','い','う','え','お','か','き','く','け','こ','さ','し','す','せ','そ','た','ち','つ','て','と','な','に','ぬ','ね','の','は','ひ','ふ','へ','ほ','ま','み','む','め','も','や','ゆ','よ','ら','り','る','れ','ろ','わ','を','ん'],
  voiced: ['が','ぎ','ぐ','げ','ご','ざ','じ','ず','ぜ','ぞ','だ','ぢ','づ','で','ど','ば','び','ぶ','べ','ぼ','ぱ','ぴ','ぷ','ぺ','ぽ'],
  contracted: ['きゃ','きゅ','きょ','しゃ','しゅ','しょ','ちゃ','ちゅ','ちょ','にゃ','にゅ','にょ','ひゃ','ひゅ','ひょ','みゃ','みゅ','みょ','りゃ','りゅ','りょ']
};
const labels = {
  zh:{practiceSet:'练习词库',chooseSet:'选择练习内容',setHint:'选择需要练习的假名范围，再开始书写练习。',vocabulary:'词库',customSelection:'手动选择',selectAll:'全选',startPractice:'开始练习',readyEyebrow:'准备练习',readyTitle:'开始假名书写练习',readyHint:'请先选择词库或假名范围。开始后将生成随机练习列表。',listenAndWrite:'根据罗马音书写对应假名',skip:'跳过',writingArea:'书写区',shortcut:'使用鼠标或手指书写',pencil:'铅笔',eraser:'橡皮',undo:'撤回',clear:'清除笔迹',next:'下一题 →',showAnswer:'显示答案',hideAnswer:'隐藏答案',normal:'普通',voiced:'第一等级变形',contracted:'加上 ya / yu / yo 的格式',question:'第 {n} / {total} 题',roman:'罗马音：{roman}',readyProgress:'准备开始'},
  ja:{practiceSet:'練習セット',chooseSet:'練習をえらぶ',setHint:'練習するひらがなを選択してから始めましょう。',vocabulary:'単語帳',customSelection:'手動で選ぶ',selectAll:'すべて選択',startPractice:'練習をはじめる',readyEyebrow:'練習の準備',readyTitle:'かな書き取り練習',readyHint:'セットを選び、開始するとランダムな問題が作られます。',listenAndWrite:'ローマ字を見て書こう',skip:'スキップ',writingArea:'書くところ',shortcut:'マウスか指で書けます',pencil:'えんぴつ',eraser:'けしごむ',undo:'元に戻す',clear:'消去',next:'つぎへ →',showAnswer:'答えを見る',hideAnswer:'答えを隠す',normal:'基本',voiced:'濁音・半濁音',contracted:'拗音（ゃ / ゅ / ょ）',question:'{n} / {total} 問',roman:'ローマ字：{roman}',readyProgress:'準備中'},
  ko:{practiceSet:'연습 세트',chooseSet:'연습을 선택하세요',setHint:'연습할 히라가나를 선택한 다음 시작하세요.',vocabulary:'단어장',customSelection:'직접 선택',selectAll:'전체 선택',startPractice:'연습 시작',readyEyebrow:'연습 준비',readyTitle:'가나 쓰기 연습',readyHint:'세트를 선택하고 시작하면 무작위 문제가 생성됩니다.',listenAndWrite:'로마자를 보고 써 보세요',skip:'넘기기',writingArea:'쓰기 영역',shortcut:'마우스나 손가락으로 쓰세요',pencil:'연필',eraser:'지우개',undo:'실행 취소',clear:'지우기',next:'다음 →',showAnswer:'정답 보기',hideAnswer:'정답 숨기기',normal:'기본',voiced:'1단 변형',contracted:'ya / yu / yo 조합',question:'{n} / {total} 번',roman:'로마자: {roman}',readyProgress:'준비 중'},
  en:{practiceSet:'Practice set',chooseSet:'Choose practice content',setHint:'Select the kana to practice before starting.',vocabulary:'Vocabulary set',customSelection:'Choose manually',selectAll:'Select all',startPractice:'Start practice',readyEyebrow:'Practice setup',readyTitle:'Kana writing practice',readyHint:'Choose a set, then start to generate a randomized practice list.',listenAndWrite:'Write the kana for this romaji',skip:'Skip',writingArea:'Writing area',shortcut:'Write with mouse or finger',pencil:'Pencil',eraser:'Eraser',undo:'Undo',clear:'Clear strokes',next:'Next →',showAnswer:'Show answer',hideAnswer:'Hide answer',normal:'Basic',voiced:'Level 1 variations',contracted:'ya / yu / yo forms',question:'Question {n} / {total}',roman:'Romaji: {roman}',readyProgress:'Ready'}
};
const vocabulary={zh:{all:'全部假名',basic:'基础五十音',voiced:'变形假名',contracted:'拗音练习'},ja:{all:'すべてのひらがな',basic:'基本の五十音',voiced:'濁音・半濁音',contracted:'拗音'},ko:{all:'모든 히라가나',basic:'기본 오십음',voiced:'변형 히라가나',contracted:'요음 연습'},en:{all:'All hiragana',basic:'Basic gojūon',voiced:'Voiced variations',contracted:'Contracted sounds'}};
const roman={あ:'a',い:'i',う:'u',え:'e',お:'o',か:'ka',き:'ki',く:'ku',け:'ke',こ:'ko',さ:'sa',し:'shi',す:'su',せ:'se',そ:'so',た:'ta',ち:'chi',つ:'tsu',て:'te',と:'to',な:'na',に:'ni',ぬ:'nu',ね:'ne',の:'no',は:'ha',ひ:'hi',ふ:'fu',へ:'he',ほ:'ho',ま:'ma',み:'mi',む:'mu',め:'me',も:'mo',や:'ya',ゆ:'yu',よ:'yo',ら:'ra',り:'ri',る:'ru',れ:'re',ろ:'ro',わ:'wa',を:'wo',ん:'n',が:'ga',ぎ:'gi',ぐ:'gu',げ:'ge',ご:'go',ざ:'za',じ:'ji',ず:'zu',ぜ:'ze',ぞ:'zo',だ:'da',ぢ:'ji',づ:'zu',で:'de',ど:'do',ば:'ba',び:'bi',ぶ:'bu',べ:'be',ぼ:'bo',ぱ:'pa',ぴ:'pi',ぷ:'pu',ぺ:'pe',ぽ:'po',きゃ:'kya',きゅ:'kyu',きょ:'kyo',しゃ:'sha',しゅ:'shu',しょ:'sho',ちゃ:'cha',ちゅ:'chu',ちょ:'cho',にゃ:'nya',にゅ:'nyu',にょ:'nyo',ひゃ:'hya',ひゅ:'hyu',ひょ:'hyo',みゃ:'mya',みゅ:'myu',みょ:'myo',りゃ:'rya',りゅ:'ryu',りょ:'ryo'};
const $=s=>document.querySelector(s);let language='zh',queue=[],index=0,tool='pencil',practiceStarted=false,answerVisible=false;
const t=key=>labels[language][key]||key;
function applyLanguage(){document.documentElement.lang=language;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));renderGroups();renderVocab();updateQuestion();}
function renderVocab(){const select=$('#vocabSelect'),before=select.value;select.innerHTML='';Object.entries(vocabulary[language]).forEach(([value,text])=>select.add(new Option(text,value)));select.value=before||'all';}
function renderGroups(){const root=$('#kanaGroups'),chosen=new Set(selectedKana());root.innerHTML='';Object.entries(groups).forEach(([key,kana])=>{const section=document.createElement('section');section.className='kana-group';section.innerHTML=`<div class="group-title">${t(key)}</div><div class="kana-options">${kana.map(k=>`<label><input type="checkbox" value="${k}" ${chosen.size===0||chosen.has(k)?'checked':''}><span>${k}</span></label>`).join('')}</div>`;root.append(section);});}
function selectedKana(){return[...document.querySelectorAll('.kana-options input:checked')].map(x=>x.value)}
function makeQueue(){const chosen=selectedKana();queue=[...(chosen.length?chosen:groups.normal)].sort(()=>Math.random()-.5);index=0;practiceStarted=true;$('#readyState').hidden=true;$('#exerciseState').hidden=false;updateQuestion();requestAnimationFrame(sizeCanvas);clearCanvas(false);history=[];updateUndo();}
function updateQuestion(){if(!practiceStarted){$('#progressText').textContent=t('readyProgress');$('#progressBar').style.width='0%';return}const kana=queue[index];$('#currentRoman').textContent=roman[kana]||kana;$('#questionMeaning').textContent=t('roman').replace('{roman}',roman[kana]||kana);$('#answerReveal').textContent=kana;answerVisible=false;$('#answerReveal').hidden=true;$('#answerButton').textContent=t('showAnswer');$('#progressText').textContent=t('question').replace('{n}',index+1).replace('{total}',queue.length);$('#progressBar').style.width=`${((index+1)/queue.length)*100}%`;}
function next(){if(!practiceStarted){makeQueue();return}index=(index+1)%queue.length;updateQuestion();clearCanvas(false);history=[];updateUndo();}
function toggleAnswer(){answerVisible=!answerVisible;$('#answerReveal').hidden=!answerVisible;$('#answerButton').textContent=t(answerVisible?'hideAnswer':'showAnswer');}
$('#languageSelect').onchange=e=>{language=e.target.value;applyLanguage()};$('#startPractice').onclick=makeQueue;$('#readyStart').onclick=makeQueue;$('#selectAll').onclick=()=>document.querySelectorAll('.kana-options input').forEach(i=>i.checked=true);$('#vocabSelect').onchange=e=>{const sets={all:[...groups.normal,...groups.voiced,...groups.contracted],basic:groups.normal,voiced:groups.voiced,contracted:groups.contracted},wanted=new Set(sets[e.target.value]);document.querySelectorAll('.kana-options input').forEach(i=>i.checked=wanted.has(i.value))};$('#nextButton').onclick=next;$('#skipButton').onclick=next;$('#answerButton').onclick=toggleAnswer;
const canvas=$('#writingCanvas'),ctx=canvas.getContext('2d');let drawing=false,last=null,history=[];
function updateUndo(){ $('#undoButton').disabled=history.length===0; }
function snapshot(){ if(!canvas.width||!canvas.height)return; history.push(ctx.getImageData(0,0,canvas.width,canvas.height)); if(history.length>40)history.shift(); updateUndo(); }
function undo(){ if(!history.length)return; ctx.putImageData(history.pop(),0,0); updateUndo(); }
function sizeCanvas(){const box=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;if(!box.width)return;canvas.width=box.width*ratio;canvas.height=box.height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);history=[];updateUndo()}
function clearCanvas(record=true){if(record)snapshot();ctx.clearRect(0,0,canvas.width,canvas.height)}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function draw(e){if(!drawing)return;const p=point(e);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=tool==='eraser'?28:5;ctx.strokeStyle=tool==='eraser'?'#fffdfa':'#4b4157';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p}
canvas.addEventListener('pointerdown',e=>{snapshot();drawing=true;last=point(e);canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',draw);['pointerup','pointercancel','pointerleave'].forEach(event=>canvas.addEventListener(event,()=>drawing=false));
function selectTool(name){tool=name;$('#pencilButton').classList.toggle('active',name==='pencil');$('#eraserButton').classList.toggle('active',name==='eraser');$('#pencilButton').setAttribute('aria-pressed',name==='pencil');$('#eraserButton').setAttribute('aria-pressed',name==='eraser');canvas.style.cursor=name==='eraser'?'cell':'crosshair'}
$('#pencilButton').onclick=()=>selectTool('pencil');$('#eraserButton').onclick=()=>selectTool('eraser');$('#undoButton').onclick=undo;$('#clearButton').onclick=()=>clearCanvas();$('#soundButton').onclick=()=>{const kana=queue[index];speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(kana))};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}});window.addEventListener('resize',()=>practiceStarted&&sizeCanvas());applyLanguage();updateUndo();
